Repository Bouni/kicad-jlcpcb-tools, pull requests merged in 2023-08, with the labels that each got.

#356 Look for "lcsc" in key and then for C number in value
  helpers.py
Labels: bug

#354 Force Scalefactor to 1.0 if on Mac OS
  helpers.py
Labels: enhancement, MacOS

#353 Fix icon colours for dark theme
  helpers.py
Labels: enhancement

#344 partselector.py - Print out the time it took to complete the search n…
  partselector.py
Labels: enhancement
