Repository Bouni/kicad-jlcpcb-tools, pull requests merged in 2023-07, with the labels that each got.

#332 Fix breaking API change in V7.99 nightly
  helpers.py
Labels: KiCAD API

#336 Extended installation info in README
  README.md
Labels: documentation

#347 mainwindow.py - Enable / disable right toolbar buttons that require p…
  mainwindow.py
Labels: enhancement
